# Generated by Django 6.0.7 on 2026-07-28 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('event_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=80)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload_summary', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ('-received_at',),
            },
        ),
        migrations.CreateModel(
            name='EscrowPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=9)),
                ('worker_payout', models.DecimalField(decimal_places=2, max_digits=9)),
                ('captured_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('pending', 'Awaiting payment'), ('authorized', 'Funds held'), ('released', 'Released to worker'), ('refunded', 'Returned to client'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('checkout_session_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('payment_intent_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='escrow', to='jobs.job')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_payments', to='accounts.workerprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StripeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_id', models.CharField(max_length=64, unique=True)),
                ('details_submitted', models.BooleanField(default=False)),
                ('charges_enabled', models.BooleanField(default=False)),
                ('payouts_enabled', models.BooleanField(default=False)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_account', to='accounts.workerprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
