# Generated by Django 6.0.7 on 2026-08-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowpayment',
            name='checkout_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='escrowpayment',
            name='funding_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
