# Generated by Django 6.0.7 on 2026-08-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_email_notifications_user_language'),
        ('payments', '0002_escrow_funding_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowpayment',
            name='captured_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='escrowpayment',
            name='captured_payout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stripeaccount',
            name='account_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='stripeaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('account_id', ''), _negated=True), fields=('account_id',), name='one_row_per_stripe_account'),
        ),
    ]
