# Generated by Django 6.0.7 on 2026-08-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_settlement_actuals'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='handled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
