# Generated by Django 6.0.7 on 2026-08-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_webhook_lease'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeaccount',
            name='flags_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
