# Generated by Django 6.0.7 on 2026-08-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_account_flag_freshness'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowpayment',
            name='funding_key',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
