# Generated by Django 6.0.7 on 2026-07-28 16:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_seed_reference_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(choices=[('standing', 'Standing position'), ('gig', 'One-day gig')], db_index=True, max_length=16)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(max_length=4000)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(choices=[('posted', 'Posted'), ('accepted', 'Accepted'), ('escrow_held', 'Escrow held'), ('in_progress', 'In progress'), ('ended_early', 'Ended early'), ('completed', 'Completed — awaiting approval'), ('disputed', 'Disputed — under review'), ('paid_out', 'Paid out'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='posted', max_length=20)),
                ('rate_type', models.CharField(blank=True, choices=[('hourly', 'Per hour'), ('daily', 'Per day')], help_text='Per hour or per day.', max_length=16)),
                ('rate_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('rate_max', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for a single flat rate.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('position_type', models.CharField(blank=True, choices=[('temporary', 'Temporary / short term'), ('ongoing', 'Ongoing'), ('full_time', 'Full time'), ('contract', 'Contract / project-based')], max_length=16)),
                ('gig_date', models.DateField(blank=True, db_index=True, null=True)),
                ('gig_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Expected length of the day.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))])),
                ('fixed_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='accounts.workerprofile')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.clientprofile')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='core.region')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='core.trade')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, help_text='Optional. What makes you right for this one?', max_length=1500)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('selected', 'Selected'), ('passed_over', 'Not selected'), ('withdrawn', 'Withdrawn')], db_index=True, default='applied', max_length=16)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.workerprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['state', 'job_type', 'trade'], name='jobs_job_state_009229_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['region', 'state'], name='jobs_job_region__1ef67e_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fixed_pay__isnull', False), ('gig_date__isnull', False), ('gig_hours__isnull', False), ('job_type', 'gig')), models.Q(('fixed_pay__isnull', True), ('gig_date__isnull', True), ('gig_hours__isnull', True), ('job_type', 'standing')), _connector='OR'), name='job_gig_fields_match_type'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('job_type', 'gig'), ('rate_max__isnull', True), ('rate_min__isnull', True)), models.Q(('job_type', 'standing'), ('rate_min__isnull', False)), _connector='OR'), name='job_rate_fields_match_type'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('rate_max__isnull', True), ('rate_max__gte', models.F('rate_min')), _connector='OR'), name='job_rate_max_not_below_min'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('job', 'worker'), name='one_application_per_worker_per_job'),
        ),
    ]
