# Generated by Django 6.0.7 on 2026-07-31 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_workerprofile_seeking'),
        ('jobs', '0002_job_site_latitude_job_site_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_private',
            field=models.BooleanField(db_index=True, default=False, help_text='Direct offers are not listed on the public board.'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, help_text='Anything they should know before saying yes.', max_length=1500)),
                ('response_note', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Waiting on the worker'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=16)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='jobs.job')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='accounts.workerprofile')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['worker', 'status'], name='jobs_offer_worker__db7e78_idx')],
                'constraints': [models.UniqueConstraint(fields=('job', 'worker'), name='one_offer_per_worker_per_job'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('job',), name='one_pending_offer_per_job')],
            },
        ),
    ]
