# Generated by Django 6.0.7 on 2026-08-01 00:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_workerprofile_seeking'),
        ('jobs', '0003_job_is_private_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_by', models.CharField(choices=[('worker', 'Worker'), ('client', 'Client')], db_index=True, max_length=8)),
                ('fixed_pay', models.DecimalField(blank=True, decimal_places=2, help_text='Total for the day.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('gig_date', models.DateField(blank=True, null=True)),
                ('gig_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))])),
                ('note', models.CharField(blank=True, help_text='Why — one line is plenty.', max_length=300)),
                ('status', models.CharField(choices=[('pending', 'On the table'), ('accepted', 'Agreed'), ('declined', 'Turned down'), ('superseded', 'Replaced by a later offer')], db_index=True, default='pending', max_length=12)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='jobs.job')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='accounts.workerprofile')),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['job', 'status'], name='jobs_counte_job_id_6a465a_idx'), models.Index(fields=['worker', 'status'], name='jobs_counte_worker__e8d714_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('job', 'worker'), name='one_live_counter_per_worker_per_job')],
            },
        ),
    ]
