# Generated by Django 6.0.7 on 2026-08-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='use_escrow',
            field=models.BooleanField(default=True, help_text="Hold the client's payment until the day is signed off."),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(choices=[('posted', 'Posted'), ('accepted', 'Accepted'), ('escrow_held', 'Escrow held'), ('in_progress', 'In progress'), ('ended_early', 'Ended early'), ('completed', 'Completed — awaiting approval'), ('disputed', 'Disputed — under review'), ('paid_out', 'Paid out'), ('refunded', 'Refunded'), ('closed', 'Closed — settled directly'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='posted', max_length=20),
        ),
    ]
