# Generated by Django 6.0.7 on 2026-08-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_use_escrow_alter_job_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='use_escrow',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='offer_group',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
