# Generated by Django 6.0.7 on 2026-08-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_counter_use_escrow_job_offer_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='use_escrow',
            field=models.BooleanField(default=False, help_text="Hold the client's payment until the day is signed off."),
        ),
    ]
