# Generated by Django 6.0.7 on 2026-08-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_email_notifications_user_language'),
        ('core', '0002_seed_reference_data'),
        ('jobs', '0009_review_booking'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(condition=models.Q(('assigned_worker__isnull', False), ('gig_date__isnull', False), ('state__in', ['accepted', 'escrow_held', 'in_progress', 'ended_early', 'completed'])), fields=('assigned_worker', 'gig_date'), name='one_booking_per_worker_per_day'),
        ),
    ]
