# Generated by Django 6.0.7 on 2026-08-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_booking_clash'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience_wanted',
            field=models.CharField(choices=[('none', 'No experience needed — will show you'), ('some', 'Some experience helps, not essential'), ('skilled', 'Needs someone who knows the trade')], db_index=True, default='none', max_length=16),
        ),
    ]
