# Generated by Django 6.0.7 on 2026-07-28 01:36

import accounts.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('google_picture_url', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('last_active_role', models.CharField(blank=True, choices=[('worker', 'Worker'), ('client', 'Client')], max_length=16)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('-date_joined',),
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating_sum', models.PositiveIntegerField(default=0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('flagged_for_review', models.BooleanField(db_index=True, default=False)),
                ('flagged_reason', models.CharField(blank=True, max_length=255)),
                ('flagged_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('jobs_posted', models.PositiveIntegerField(default=0)),
                ('jobs_completed', models.PositiveIntegerField(default=0)),
                ('jobs_cancelled', models.PositiveIntegerField(default=0)),
                ('approval_seconds_total', models.BigIntegerField(default=0)),
                ('approvals_counted', models.PositiveIntegerField(default=0)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='core.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating_sum', models.PositiveIntegerField(default=0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('flagged_for_review', models.BooleanField(db_index=True, default=False)),
                ('flagged_reason', models.CharField(blank=True, max_length=255)),
                ('flagged_at', models.DateTimeField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=accounts.models.photo_upload_path)),
                ('service_area', models.CharField(blank=True, max_length=200)),
                ('years_experience', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('rate_type', models.CharField(choices=[('hourly', 'Per hour'), ('daily', 'Per day')], default='hourly', max_length=16)),
                ('rate_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('rate_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('availability_status', models.CharField(choices=[('available_now', 'Available now'), ('specific_days', 'Specific days'), ('ongoing', 'Open to ongoing work'), ('unavailable', 'Not currently available')], default='available_now', max_length=20)),
                ('availability_note', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True, max_length=2000)),
                ('cv', models.FileField(blank=True, help_text='Optional PDF résumé.', null=True, upload_to=accounts.models.cv_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('jobs_accepted', models.PositiveIntegerField(default=0)),
                ('jobs_completed', models.PositiveIntegerField(default=0)),
                ('jobs_disputed', models.PositiveIntegerField(default=0)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='core.region')),
                ('trades', models.ManyToManyField(related_name='workers', to='core.trade')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PortfolioPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=accounts.models.portfolio_upload_path)),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_photos', to='accounts.workerprofile')),
            ],
            options={
                'ordering': ('display_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='TradeLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=80)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_note', models.CharField(blank=True, max_length=255)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='core.trade')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='accounts.workerprofile')),
            ],
            options={
                'unique_together': {('worker', 'trade')},
            },
        ),
        migrations.CreateModel(
            name='AvailabilityDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_dates', to='accounts.workerprofile')),
            ],
            options={
                'ordering': ('date',),
                'unique_together': {('worker', 'date')},
            },
        ),
    ]
