# Generated by Django 6.0.7 on 2026-07-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='open_to_full_time',
            field=models.BooleanField(blank=True, help_text='Full-time positions are posted as standing jobs, not day gigs.', null=True, verbose_name='Open to a full-time job?'),
        ),
    ]
