# Generated by Django 6.0.7 on 2026-07-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar_user_date_of_birth_user_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='seeking',
            field=models.CharField(blank=True, help_text='Shown at the top of your profile. Change it as often as you like.', max_length=200, verbose_name='What are you looking for right now?'),
        ),
    ]
