# Generated by Django 6.0.7 on 2026-07-29 14:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_workerprofile_open_to_full_time'),
        ('jobs', '0002_job_site_latitude_job_site_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('accuracy_m', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_m', models.PositiveIntegerField(blank=True, null=True)),
                ('looks_on_site', models.BooleanField(blank=True, null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_in', to='jobs.job')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='accounts.workerprofile')),
            ],
            options={
                'ordering': ('-arrived_at',),
            },
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hours_worked', models.DecimalField(decimal_places=1, max_digits=4)),
                ('ended_early', models.BooleanField(default=False)),
                ('ended_early_by', models.CharField(blank=True, choices=[('worker', 'Worker'), ('client', 'Client')], max_length=8)),
                ('early_end_note', models.CharField(blank=True, max_length=300)),
                ('payable_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('settles_at', models.DateTimeField(db_index=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='jobs.job')),
            ],
            options={
                'ordering': ('-finished_at',),
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('open', 'Awaiting review'), ('resolved_worker', 'Resolved — paid to worker'), ('resolved_client', 'Resolved — refunded to client')], db_index=True, default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, max_length=2000)),
                ('resolved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='jobs.job')),
                ('raised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_raised', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
