# Generated by Django 6.0.7 on 2026-08-18 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0008_alter_job_use_escrow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('message', 'New message'), ('offer_received', 'You were offered a job'), ('offer_answered', 'Your offer was answered'), ('application', 'Somebody applied to your job'), ('selected', 'You were picked for a job'), ('work_finished', 'The work was marked finished'), ('job_closed', 'A job was closed'), ('escrow_funded', 'Escrow was funded'), ('payment_released', 'A payment was released'), ('dispute', 'A dispute was raised'), ('rating', 'You were rated')], db_index=True, max_length=32)),
                ('booking', models.UUIDField(blank=True, db_index=True, null=True)),
                ('dedupe_key', models.CharField(blank=True, max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='jobs.job')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['sent_at', 'created_at'], name='notificatio_sent_at_13cbdb_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('sent_at__isnull', True), models.Q(('dedupe_key', ''), _negated=True)), fields=('recipient', 'dedupe_key'), name='one_pending_notification_per_key')],
            },
        ),
    ]
