# Generated by Django 6.0.7 on 2026-08-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('message', 'New message'), ('job_posted', 'New work in your trade'), ('reminder', 'Something is waiting for you'), ('offer_received', 'You were offered a job'), ('offer_answered', 'Your offer was answered'), ('application', 'Somebody applied to your job'), ('selected', 'You were picked for a job'), ('work_finished', 'The work was marked finished'), ('job_closed', 'A job was closed'), ('escrow_funded', 'Escrow was funded'), ('payment_released', 'A payment was released'), ('dispute', 'A dispute was raised'), ('rating', 'You were rated')], db_index=True, max_length=32),
        ),
    ]
